### ISSUE TITLE
Question on authoring approach 

### ISSUE THREAD

**Issue by huntc** [codelabsab/rust-ocpp#1]
Thanks for this library!

Just curious as to how you went about authoring these types initially- from OCPP provided json schema, or manually? Thanks.

**Comment by tommymalmqvist** [comment]
Hi and thanks for the comment. I'm sorry I haven't had the time to work on this further lately. 

I was looking into a library for doing that automatically but the json schema version was too old if I remember correctly.

**Comment by tommymalmqvist** [comment]
I have done it manually but I can't be 100% certain the implementation is correct.

It is on my todo to make some kind of formal verification.

**Comment by huntc** [comment]
Thanks!

**Comment by tommymalmqvist** [comment]
@huntc I know this issue is closed but v2.0.1 has been validated against the schema files now. The tests are available in the repo: https://github.com/codelabsab/rust-ocpp/blob/main/ocpp/src/v2_0_1/tests/schema_validation.rs

**Comment by huntc** [comment]
Thank you so much for the follow up! It is quite timely for us as we have OCPP integration in our sites.
