### ISSUE TITLE
OCPP1.6 Missing Option for timestamp in StatusNotificationRequest

### ISSUE THREAD

**Issue by StaticVoidMoon** [codelabsab/rust-ocpp#10]
Hi Code Labs,

For OCPP1.6, I think there is a minor error in StatusNotificationRequest.
According to the document the timestamp field for StatusNotificationRequest should be an optional field.

```
pub struct StatusNotificationRequest {
    pub connector_id: u64,
    pub error_code: ChargePointErrorCode,
    pub info: Option<String>,
    pub status: ChargePointStatus,
    pub timestamp: DateTime<Utc>, <-- Option<DateTime<Utc>> I think
    pub vendor_id: Option<String>,
    pub vendor_error_code: Option<String>,
}
```

I am still beginner in both rust and ev field, so I am sorry if this is my misunderstanding.
Thanks.

**Comment by tommymalmqvist** [comment]
Hello @StaticVoidMoon, I'll have a look later today. Thanks for the issue.
