### ISSUE TITLE
Version 1.0.5 introduced breaking changes.

### ISSUE THREAD

**Issue by Erk-** [codelabsab/rust-ocpp#114]
The version released at https://github.com/codelabsab/rust-ocpp/releases/tag/v1.0.5 contains a breaking change introduced in https://github.com/codelabsab/rust-ocpp/pull/110.

## What should be done?
I would say to yank version 1.0.5 and instead release it as version 2.0.0.

**Comment by tommymalmqvist** [comment]
Thank you, I'll do that

**Comment by tommymalmqvist** [comment]
v2.0.0 released with information about breaking changes
