### ISSUE TITLE
Fix code coverage

### ISSUE THREAD

**Issue by parberge** [codelabsab/rust-ocpp#116]
Seems like we have code coverage that is supposed to run in CI, but it doesn't seem to work properly:
<img width="947" alt="image" src="https://github.com/user-attachments/assets/23b1cfb9-a735-4022-8d2f-db8e89d262e2">

So either we should fix it or remove it.

**Comment by tommymalmqvist** [comment]
Merged codecov 5.0.2

**Comment by parberge** [comment]
The same error still occurs though?

**Comment by tommymalmqvist** [comment]
Updated the token, looks like it works now
