### ISSUE TITLE
Add support for types declared in OCPP JSON Specification (RPC Framework)

### ISSUE THREAD

**Issue by anthonyjmartinez** [codelabsab/rust-ocpp#15]
First, thanks for providing this crate with all of the various types handled quite nicely. This has allowed me to rapidly prototype clients and servers in Rust.

Both 1.6 and 2.0.1 include an additional sheet where the RPC Framework is defined, and in each spec there are three message types into which all of the various structs and enums already created fit:
1. Call
2. CallResult
3. CallError

While I have implemented these myself to allow for processing of received JSON messages into an enum from which I can use match semantics, I can't help but think there's room for these convenience types within this project directly.

Example follows:
```rust
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Deserialize, Serialize, Debug)]
enum Action {
    Heartbeat,
    // Fill this with all possible Action values for a Call
}

#[derive(Deserialize, Serialize, Debug)]
enum ErrorCode {
    NotImplemented,
    NotSupported,
    InternalError,
    ProtocolError,
    SecurityError,
    FormationViolation,
    PropertyConstraintViolation,
    OccurenceConstraintViolation,
    TypeConstraintViolation,
    GenericError,
}

#[derive(Deserialize, Serialize, Debug)]
struct CallData {
    msg_type_id: u8,
    unique_id: String,
    action: Action,
    payload: Value,
}

#[derive(Deserialize, Serialize, Debug)]
struct CallResultData {
    msg_type_id: u8,
    unique_id: String,
    payload: Value,
}

#[derive(Deserialize, Serialize, Debug)]
struct CallErrorData {
    msg_type_id: u8,
    unique_id: String,
    error_code: ErrorCode,
    error_description: String,
    error_details: Value,
}

#[derive(Deserialize, Serialize, Debug)]
#[serde(untagged)]
enum OcppMessage {
    Call(CallData),
    CallResult(CallResultData),
    CallError(CallErrorData),
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let call = r#"[2, "123456", "Heartbeat", {}]"#;
    let call_result = r#"[3, "123456", {"currentTime": "2023-04-05T17:20:00.000Z"}]"#;
    let call_error = r#"[4, "987654", "NotImplemented", "", {}]"#;

    let c: OcppMessage = serde_json::from_str(call)?;
    let d: OcppMessage = serde_json::from_str(call_result)?;
    let e: OcppMessage = serde_json::from_str(call_error)?;

    println!("{c:?}");
    // Call(CallData { msg_type_id: 2, unique_id: "123456", action: Heartbeat, payload: Object {} })
    println!("{d:?}");
    // CallResult(CallResultData { msg_type_id: 3, unique_id: "123456", payload: Object {"currentTime": String("2023-04-05T17:20:00.000Z")} })
    println!("{e:?}");
    // CallError(CallErrorData { msg_type_id: 4, unique_id: "987654", error_code: NotImplemented, error_description: "", error_details: Object {} })
    Ok(())
}
```

If this is something the project would be interested in including, I'm happy to help. For my uses, I will be implementing TryFrom for various messages to handle the conversion of the `Value` fields into the types this crate already provides.

**Comment by tommymalmqvist** [comment]
Hi @anthonyjmartinez and thank you for the input ⭐️

I totally see your point, as I did start an implementation of a server and started writing a RPC-module for this. You can check out the source code here: [ocpp-csms-server](https://github.com/codelabsab/ocpp-csms-server/tree/main/src/rpc)

I was exploring different ideas on how to get it right, use enums or some other way, but never finished the work. I dove into the whole state machines in rust, for the server,  and then life just decided it had other plans for me.

So for now I will leave it up to anyone who want's to implement a server to handle the rpc stuff.

I'm glad someone's using this at least :)

**Comment by tommymalmqvist** [comment]
Read previous comment
