### ISSUE TITLE
Consider putting 1.6 and 2.0 support behind feature flags

### ISSUE THREAD

**Issue by shepmaster** [codelabsab/rust-ocpp#18]
I'm playing around a bit, but my solitary charge point only supports 1.6 so all the references to 2.0 stuff in the docs and rust-analyzer autocomplete are basically just noise to me.

Would you accept a PR putting each module behind a feature flag?

**Comment by tommymalmqvist** [comment]
Hello @shepmaster, yes that sounds like a good idea 👍

**Comment by tommymalmqvist** [comment]
I will close this issue but you are welcome to send PRs

**Comment by shepmaster** [comment]
Thanks for doing this! I was going to get around to it... someday... ❤️

**Comment by tommymalmqvist** [comment]
No problem my friend, enjoy ❤️
