### ISSUE TITLE
Real app examples using the lib

### ISSUE THREAD

**Issue by alex-vergara-ecomt** [codelabsab/rust-ocpp#2]
Hello. 

I would like to request about info of where I can find some real projects using this Rust library, or if you have one (like a server for management) to find an example.

Thanks in advice

**Comment by tommymalmqvist** [comment]
Hi Alexa, we only have some internal stuff written which are not open-sourced yet. I have not had the time to work on the project lately unfortunately.

What is missing mostly is verifying the implementation but I got stuck on verifying the jsonschema v6 against the implementation. There was no support for draft 6 if I remember correctly.

**Comment by alex-vergara-ecomt** [comment]
Oh! Okey, that's understandable.

I just have to write some app in Java and I would like to prefer to choose Rust :D 

Hope you guys found time for work on the project.

Thanks for your efforts.
