### ISSUE TITLE
OCPP1.6: size of integer for transaction_id

### ISSUE THREAD

**Issue by laurst** [codelabsab/rust-ocpp#27]
Thank you very much for this library. While using it, I found some poles implementing OCPP 1.6 that expect 32bits integer for transaction_id instead of 64bits as it is specified in the messages here. Reading the OCPP standard, I could not find any place where the size of integers is defined (they just specify `integer` both in the documentation and in the json validation files).

Do you have more information about what OCPP specifies here?

I'd be happy to provide a PR if you want to switch to i32; on the other hand, 32bit is not a lot of entropy for a distributed system and I'd have preferred to use at least 64 bits, so I understand if you're happy to leave things as they are.

**Comment by tommymalmqvist** [comment]
Hi @laurst, thank you for your input. You are actually correct, the specification states 32-bit so I'd happily take a PR :)

From the specification:

**Integer**
32 bit (31 bit resolution, 1 sign bit)
No leading 0’s No plus sign
Allowed value examples: 1234, -1234
Not Allowed: 01234, +1234

**Comment by tommymalmqvist** [comment]
Hi @laurst this is nagging me so I'll fix it :) Thanks tho, totally missed this.

**Comment by laurst** [comment]
That was quick, thanks! I have to ask though, in which document do you see this specified? I've searched in both the 1.6 edition 2 spec, the erratas, the json spec, and I might be dense but I didn't see it.

**Comment by tommymalmqvist** [comment]
file: OCPP-2.0.1_part2_specification.pdf

2.1.3. Primitive Datatypes

**Comment by SirVer** [comment]
@tommymalmqvist This seems to be only for 2.0.1, is this also specified for 1.6?

**Comment by tommymalmqvist** [comment]
@SirVer No, 1.6 has not defined it. Do you need 64-bit for 1.6? Else I think it'll be more safe to use 32-bit if there are many Pole's running on 32-bit.
