### ISSUE TITLE
Web socket 

### ISSUE THREAD

**Issue by siddharth1729** [codelabsab/rust-ocpp#32]
It's just a great codebase that I'm looking into, and I'm also trying to contribute to it."

Few questions:

1) It seems that the WebSocket part of OCPP is not included in this project, so it may focus solely on CPMS (Charge Point Management System) functionality.

2) If someone needs to implement the core OCPP WebSocket functionality in Rust, could you suggest some resources?

**Comment by tommymalmqvist** [comment]
Hello, yes I think the best option would be to look at other languages, Golang for example has a more feature complete library.

**Comment by tommymalmqvist** [comment]
@siddharth1729 checkout this repo also: https://github.com/shepmaster/rust-charge
