### ISSUE TITLE
Consider publishing git tags and a changelog

### ISSUE THREAD

**Issue by shepmaster** [codelabsab/rust-ocpp#58]
I'm on version 0.4.1 and 0.4.4 is available, but I have yet to find what the differences are between the versions. Having a changelog would be wonderful to get a quick idea of what to expect, and git tags would allow me to dive into detail on differences.

Thanks!

**Comment by parberge** [comment]
Sounds reasonable to me. At least tagging to make it easy to compare versions

**Comment by tommymalmqvist** [comment]
@shepmaster Very good idea! Will implement for future releases
