### ISSUE TITLE
LOCAL_AUTH_LIST_MAX_LENGTH has incorrect value

### ISSUE THREAD

**Issue by devanlai** [codelabsab/rust-ocpp#70]
It's not actually used within the crate, but the value of `rust_ocpp::v1_6::messages::change_configuration::LOCAL_AUTH_LIST_MAX_LENGTH` is incorrect; right now it's `"LocalAuthListEnabled"`, probably copied and pasted from `LOCAL_AUTH_LIST_ENABLED`.

**Comment by tommymalmqvist** [comment]
@devanlai Thank you, I'll check it out
