### ISSUE TITLE
ValueFormat not accessible

### ISSUE THREAD

**Issue by darxkies** [codelabsab/rust-ocpp#81]
ValueFormat in v1_6 is not public.

**Comment by tommymalmqvist** [comment]
You mean here? https://github.com/codelabsab/rust-ocpp/blob/82216bb7edb1f1c2ad8fe6ff81fdb6b0c58345a8/src/v1_6/types/value_format.rs#L3

**Comment by tommymalmqvist** [comment]
You can checkout this one if you want to test

https://github.com/codelabsab/rust-ocpp/pull/93

**Comment by darxkies** [comment]
When I reported the bug I made the same change locally and it worked.
