### ISSUE TITLE
Incorrect enum for GetInstalledCertificateIdsResponse.status

### ISSUE THREAD

**Issue by devanlai** [codelabsab/rust-ocpp#90]
It appears there is a typo: right now `GetInstalledCertificateIdsResponse`'s `status` field is using `GetDisplayMessagesStatusEnumType` instead of `GetInstalledCertificateStatusEnumType`.

The two enums are not equivalent; `GetDisplayMessagesStatusEnumType` defines `Accepted` and `Unknown` whereas `GetInstalledCertificateStatusEnumType` defines `Accepted` and `NotFound`.

**Comment by tommymalmqvist** [comment]
Hello,

Thank you so much. I will look into this as soon as possible.
