### ISSUE TITLE
rust_ocpp::v1_6::types::AuthorizationData serializes as snake_case instead of camelCase

### ISSUE THREAD

**Issue by devanlai** [codelabsab/rust-ocpp#98]
The v1.6 version of `AuthorizationData` is missing the `#[serde(rename_all = "camelCase")]` attribute needed to rename the fields to match the v1.6 specification.

**Comment by tommymalmqvist** [comment]
Releasing v1.0.4 to crates.io right now, thank you.

**Comment by devanlai** [comment]
Thanks for the quick response!
